spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cardmanager_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml


springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: SECRET

security:
  encryption-key: MySecretKey69420
